### ISSUE TITLE
Removing excess curly braces after `macro`?

### ISSUE THREAD

**Issue by player-03** [thispolo/haxe-delegates#7]
I notice you [always include curly braces after `macro`](https://github.com/thispolo/haxe-delegates/blob/51c6959218dcf4b719b730d324d48530d1569495/src/hx/delegates/DelegateBuilder.hx#L277-L281), even when not required. Do you prefer it that way, or are you just doing that because it's what works? In the latter case, I'd like to argue for removing them. They aren't actually required, you just have to remember _not_ to add a semicolon.

In my opinion, removing the braces makes both the source code and the output code easier to read. For instance, here's what happens if you [remove them from `createInstantiation()`](https://try.haxe.org/#EF416469):

```haxe
import haxe.macro.Expr;
import haxe.macro.Printer;

class Test {
  static function main() {
    var typePath:TypePath = {pack: [], name: "Test"};
    var inVars:Array<String> = ["a", "b", "c"];
    
    trace(new Printer().printExpr(createInstantiation(typePath, inVars))); //{ new Test({ this; }, { a; }, { b; }, { c; }); }
    trace(new Printer().printExpr(createInstantiation2(typePath, inVars))); //new Test(this, a, b, c)
  }
	
  private static function createInstantiation(typePath : TypePath, inVars : Array<String>) : Expr {
    var exprs = [for(name in inVars) macro {$i{name}}];
    exprs.insert(0, macro {this;});
    return macro {new $typePath($a{exprs});};
  }
	
  private static function createInstantiation2(typePath : TypePath, inVars : Array<String>) : Expr {
    var exprs = [for(name in inVars) macro $i{name}];
    exprs.insert(0, macro this);
    return macro new $typePath($a{exprs});
  }
}
```

Basically `macro` parses all following code until it finds a token that doesn't match. So for `exprs.insert(0, macro this)`, the right paren ends the macro because there's no left paren in the macro. If `insert()` took a third argument, you could also use a comma to end the macro. As for `return macro new $typePath($a{exprs});`, macros don't normally need or want semicolons, so placing a semicolon ends the macro. You only get to add semicolons if you make a block expression (such as `return macro {new $typePath($a{exprs});};`).

It takes some getting used to, but it's quite reliable. Off the top of my head, `EVars` is the only expression that can produce any ambiguity whatsoever, and that's easy to work around.

---

One final reason to consider this change: what if you ever have to parse a macro-generated expression? Parsing `EBlock([{expr:EConst(CIdent(s))}])` is slightly harder than parsing `EConst(CIdent(s))`.

**Comment by paulsgcross** [comment]
Yep, totally agree that it looks cleaner. It's definitely not a preference on my part as I am still learning the nuances of macros.

I am happy to scrub out the redundant braces on a subsequent patch as well as clean up the macro in general :)

**Comment by player-03** [comment]
Great! I'd be happy to help with the cleanup too.
